// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhqawndxfpmcdwnrijht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZocWF3bmR4ZnBtY2R3bnJpamh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MjY4ODQsImV4cCI6MjA2MzMwMjg4NH0.-siUNGOKtJeEvzOlLM9OjONtvX8K4J2PWPQw1sx-LMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);